CREATE DATABASE e_commerce;
USE e_ecommerce;

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(200)NOT NULL UNIQUE,
phone VARCHAR(34),
date_of_birth DATE,
address VARCHAR(200)
);

CREATE TABLE products (
id INT AUTO_INCREMENT PRIMARY KEY,
productName VARCHAR(200),
price DECIMAL(10,2) NOT NULL,
color VARCHAR(200),
stock INT DEFAULT 0,
status ENUM('ACTIVE', 'DISCONTINUED', 'OUT_OF_STOCK') DEFAULT 'ACTIVE',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orders (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
order_date DATETIME DEFAULT CURRENT_TIMESTAMP,
status ENUM('PENDING','PAID','SHIPPED','CANCELLED') DEFAULT 'PENDING',
total_amount DECIMAL(10,2) DEFAULT 0.00,
shipping_address VARCHAR(200),

FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (product_id) REFERENCES product(id),
FOREIGN KEY (orders_id) REFERENCES orders(id)

);


